---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph-py-example
  labels:
    app: graph-py-example
  annotations:
    repository: "https://github.com/vorendu-com/federated-python-example"
    owner: "@llasapg"
  namespace: "prod"
spec:
  selector:
    matchLabels:
      app: graph-py-example
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: graph-py-example
      annotations:
        repository: "https://github.com/vorendu-com/federated-python-example"
        owner: "@llasapg"
    spec:
      containers:
        - name: graph-py-example
          image: vorendureg.azurecr.io/federated-python-example:b88d31c02153b61cd7c3e6cc3c9520e223d11be7
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: Test_Env
              value: "123"
            - name: Test_Env2
              value: "123"
          resources:
            requests:
              memory: "40Mi"
              cpu: "10m"
            limits:
              memory: "150Mi"
              cpu: "150m"
          livenessProbe:
            failureThreshold: 1
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            tcpSocket:
              host: ""
              port: 80
          readinessProbe:
            failureThreshold: 1
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
            tcpSocket:
              host: ""
              port: 80
          startupProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 8
            tcpSocket:
              host: ""
              port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: graph-py-example
  annotations:
    repository: "https://github.com/vorendu-com/federated-python-example"
    owner: "@llasapg"
  namespace: "prod"
spec:
  type: ClusterIP
  ports:
    - name: graph-py-example
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: graph-py-example

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graph-py-example
  annotations:
    repository: "https://github.com/vorendu-com/federated-graph-gateway"
    owner: "@llasapg"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: "prod"
spec:
  rules:
  - host: graph-py-test.vorendu.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: graph-py-example
            port:
              number: 80
