name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  appName: federated-python-example

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Build and push image"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          branch_name=$(echo ${{ github.ref }} | sed -e "s/refs\/heads\///")
          short_sha=$(echo ${{ github.sha }} | cut -c 1-7)
          version_tag="${branch_name}-${short_sha}"
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/$appName:${version_tag}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$appName:${version_tag}

